---
apiVersion: v1
kind: Namespace
metadata:
  name: tatesremedies
---
#kind: ConfigMap
#apiVersion: v1
#metadata:
#  name: qcguy-configmap
#  namespace: qcguy
#data:
  # Configuration values can be set as key-value properties
  #database: mongodb
  #database_uri: mongodb://localhost:27017
  # Or set as complete file contents (even JSON!)
#  fromfile: /home/vik/IdeaProjects/qcguy-cms/config/
---
apiVersion: v1
kind: Service
metadata:
  name: tatesremedies
  namespace: tatesremedies
  labels:
    app: tatesremedies
    io.kompose.service: tatesremedies
spec:
  type: NodePort
  #loadBalancerIP: 192.168.49.234
  selector:
    io.kompose.service: tatesremedies
    app: tatesremedies
  ports:
    - port: 2369
      protocol: TCP
      name: "2369"
      nodePort: 30369
      targetPort: 2369
  #externalTrafficPolicy: Local
status:
  #loadBalancer:
  #  ingress:
  #    - ip: 192.168.49.234
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tatesremedies-pv-volume
  namespace: tatesremedies
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/tatesremedies
#  storageClassName: do-block-storage
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: qcguy-content
#  labels:
#    app: qcguy-content
#spec:
#  storageClassName: ""
#  capacity:
#    storage: 250Mi
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  claimRef:
#    namespace: qcguy
#    name: qcguy-content
#  nfs:
#    path: /tmp
#    server: 172.17.0.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: tatesremedies-content-claim
  namespace: tatesremedies
  labels:
    app: tatesremedies-content-claim
    io.kompose.service: tatesremedies-content-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: manual
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    app: tatesremedies
    io.kompose.service: tatesremedies
  name: tatesremedies
  namespace: tatesremedies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tatesremedies
      io.kompose.service: tatesremedies
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: tatesremedies
        app: tatesremedies
    spec:
      volumes:
        - name: tatesremedies-content-storage
          persistentVolumeClaim:
            claimName: tatesremedies-content-claim
        - name: tatesremedies-configmap-volume
          configMap:
            name: tatesremedies-configmap
            #items:
            # - key: config.production.json
            #    path: "./var/lib/ghost/config.production.json"
      containers:
        #- env:
        #    - name: url
        #      value: https://www.tatesremedies.com
        - image: ghost:latest
          #imagePullPolicy: Always
          name: tatesremedies
          ports:
            - containerPort: 2369
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/ghost/content #/mnt/qcguy-ghost/data
              name: tatesremedies-content-storage
            - name: tatesremedies-configmap-volume
              mountPath: /var/lib/ghost/config.production.json #/mnt/qcguy-ghost/data/data/config.production.json
              subPath: config.production.json
      #restartPolicy: Never
status: {}